config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # # /admin/...
  # namespace :admin do
  #   # The `namespace` method takes a symbol as a first argument
  #   # and a block. It will prefix the symbol's name to the
  #   # path of all routes defined inside the block.
  #   # GET /admin/dashboard
  #   resources :dashboard, only: [:index]

  #   # It will expect that the controllers for the routes
  #   # inside block to be contained in a module named after
  #   # the symbol.
  #   # Example: Admin::DashboardController

  #   # It will also expect the controllers to be in a sub-directory
  #   # named after the symbol.
  #   # Example: /app/controllers/admin/dashboard_controller.rb

  #   # GET /admin/users
  #   # POST /admin/users
  #   # GET /admin/users/:id
  #   # resources :users
  
    # `resource` is singular instead of `resources`.
  # Unlike `resources`, `resource` will create routes
  # that do CRUD operation on only one thing. There
  # will be no index routes and no route will
  # have a `:id` wild card. When using a singular resource,
  # the controller must still be plural.
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :edit]
  
    
  

  resources :posts do
    #get :my_route
    resources :comments, only: [:create, :destroy]

    # The above method call `resources :questions`
  # will exactly create all RESTful routes as written below:
  end
  # we map HTTP verb/url combo to a controller#action (action is a method inside the controller class)
  get('/', { to: 'posts#index', as: 'home' })

  get('/comment', { to: 'comment#index' })
  post('/comment_submit', { to: 'comment#create' })
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
    
    validates(:title, presence: true, uniqueness: true)

    validates(
        :title,
        presence: true,
          uniqueness: true
    )
        validates(
        :body,
        presence: true,
          length: {
              minimum: 50
          }
      )  
end


  # answers
  # answers<<(object, ...)
  # answers.delete(object, ...)
  # answers.destroy(object, ...)
  # answers=(objects)
  # answer_ids
  # answer_ids=(ids)
  # answers.clear
  # answers.empty?
  # answers.size
  # answers.find(...)
  # answers.where(...)
  # answers.exists?(...)
  # answers.build(attributes = {}, ...)
  # answers.create(attributes = {})
  # answers.create!(attributes = {})
  # answers.reload

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]  
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
        @post = Post.new
  end
  
  def create
      # The `params` object available in controllers
      # is composed of the query string, url params and the
      # body of a form (e.g. req.query + req.params + req.body)
  
      # A good trick to see if your routes work and you're getting
      # data that you want is rendering the params as JSON. This
      # is like doing res.send(req.body) in Express.
      #render json: params
  
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      #redirect_to home_path
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def show
      #@post = Post.find params[:id]
      #@post.view_count += 1 # me cut out
    @post.save
        #render json: params
        ##render json: @post
        ###render :show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def index
    @posts = Post.order(created_at: :desc)
        # render json: @posts
  end
    
  def edit
        #@post = Post.find params[:id]
  end
    
  def update
    #render json: params
    #@post = Post.find params[:id]

    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    #@post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end


  private
  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user!
    unless can?(:manage, @post)
      flash[:danger] = "Access Denied"
      redirect_to post_path(@post)
    end
  end
end

app/views/posts/_form.html.erb
<br clear="all">
<div class="margin50">


<%= form_for(@post) do |f| %>
  <% if @post.errors.present? %>
    <p>
      <%= @post.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <br clear="all">
  <div>
    <%= f.label(:title) %><br>
    <%= f.text_field(:title, class: "hundyP") %>
  </div>

  <div class="marginTop">
    <%= f.label(:body) %><br>
    <%= f.text_area(:body, rows: 6, class: "hundyP") %>
  </div>



  <%= f.submit(class: "btn btn-outline-primary marginTop") %>
<% end %>

</div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<br clear="all">
<div class="margin40">
  <% @posts.each do |post| %>
    <div class="container">
      <div class="card-body">
        <%= link_to post.title, post_path(post.id) %>
        <br />
          <small>
            Posted <%= time_ago_in_words(post.created_at) %> ago
          </small>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<br clear="all">
<div class="margin50">
<h2><%= @post.title %></h2>

<p><%= @post.body %></p>

<p>By <%= @post.user&.full_name || "[Deleted]" %></p>

<div>
  <small>
    Posted <%= time_ago_in_words(@post.created_at) %> ago
  </small>
  •
  <small>
    Last edited <%= time_ago_in_words(@post.updated_at) %> ago
  </small>
  •

</div>
<br>

<% if user_signed_in? %>

<% if can?(:edit, @post) %>
  <div class="btn btn-outline-primary">
    <%= link_to "Edit", edit_post_path(@post) %>
  </div>
<% end %>
      
<% if can?(:delete, @post) %>
  <div class="btn btn-outline-primary">
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<% end %> 
<br>

<h2>Comments</h2>
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.present? %>
    <p>
      <%= @comment.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <%#= f.hidden_field :post_id, value: @post.id %>
  <div>
    <%= f.text_area(
      :body, rows: 6,
      class: "hundyP",
      placeholder: "What are your thoughts?"
    ) %>
  </div>
  <input type="Submit" class="btn btn-outline-primary" value="Submit">
<% end %>
<br clear="all">
<br>
<div class="answer-list">
  <% @comments.each do |comment| %>
    <div>
      <p>
      <strong>
        <%= comment.user&.full_name || "[DELETED]" %> commented:
      </strong> <br />
        <%= comment.body %> <br />

        <% if user_signed_in? && can?(:delete, comment) %>
          <small>
            <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
          </small>
          •
        <% end %>
        <small>
          Commented <%= time_ago_in_words(comment.created_at) %> ago
        </small>
      </p>
    </div>
  <% end %>
</div>
</div>